### ISSUE TITLE
DB missing

### ISSUE THREAD

**Issue by jadebatz07** [sumit-narang/Dental-clinic-management-system#1]
you forgot the db,

**Comment by mohsenuss91** [comment]
Great design  @sumit-narang.
@jadebatz07 is right!

**Comment by venkatbh** [comment]
Where is DB file??

**Comment by sumit-narang** [comment]
![image](https://user-images.githubusercontent.com/20576051/28289322-c95c01c0-6b5f-11e7-9701-0eecd2b7f4d1.png)

Added db file "dentalclinic.sql"
